export default [
    {
        title: '电影',
        obj: {
            type: [
                { checked: true, text: '全部类型' },
                { checked: false, text: '动作片' },
                { checked: false, text: '喜剧片' },
                { checked: false, text: '爱情片' },
                { checked: false, text: '科幻片' },
                { checked: false, text: '恐怖片' },
                { checked: false, text: '剧情片' },
                { checked: false, text: '战争片' },
                { checked: false, text: '动漫电影' },
            ],
            year: [
                { checked: true, text: '全部年代' },
                { checked: false, text: '2021' },
                { checked: false, text: '2020' },
                { checked: false, text: '2019' },
                { checked: false, text: '2018' },
                { checked: false, text: '2017' },
                { checked: false, text: '2016' },
                { checked: false, text: '2015' },
                { checked: false, text: '2014' },
                { checked: false, text: '2013' },
                { checked: false, text: '2012' },
                { checked: false, text: '2011' },
                { checked: false, text: '2010' },
                { checked: false, text: '2009' },
                { checked: false, text: '2008' },
                { checked: false, text: '2007' },
            ],
            city: [
                { checked: true, text: '全部地区' },
                { checked: false, text: '大陆' },
                { checked: false, text: '香港' },
                { checked: false, text: '台湾' },
                { checked: false, text: '美国' },
                { checked: false, text: '韩国' },
                { checked: false, text: '日本' },
                { checked: false, text: '泰国' },
                { checked: false, text: '新加坡' },
                { checked: false, text: '马来西亚' },
                { checked: false, text: '印度' },
                { checked: false, text: '英国' },
                { checked: false, text: '法国' },
                { checked: false, text: '加拿大' },
                { checked: false, text: '西班牙' },
                { checked: false, text: '俄罗斯' },
                { checked: false, text: '其它' },
            ],
            language: [
                { checked: true, text: '全部语言' },
                { checked: false, text: '国语' },
                { checked: false, text: '英语' },
                { checked: false, text: '粤语' },
                { checked: false, text: '闽南语' },
                { checked: false, text: '韩语' },
                { checked: false, text: '日语' },
                { checked: false, text: '法语' },
                { checked: false, text: '德语' },
                { checked: false, text: '其它' },
            ],
            sort: [
                { checked: true, text: '更新排序' },
                { checked: false, text: '人气排序' },
            ]
        }
    },
    {
        title: '电视剧',
        obj: {
            type: [
                { checked: true, text: '全部类型' },
                { checked: false, text: '国产剧' },
                { checked: false, text: '港台剧' },
                { checked: false, text: '日韩剧' },
                { checked: false, text: '欧美剧' },
                { checked: false, text: '泰国剧' },
                { checked: false, text: '海外剧' },
            ],
            year: [
                { checked: true, text: '全部年代' },
                { checked: false, text: '2021' },
                { checked: false, text: '2020' },
                { checked: false, text: '2019' },
                { checked: false, text: '2018' },
                { checked: false, text: '2017' },
                { checked: false, text: '2016' },
                { checked: false, text: '2015' },
                { checked: false, text: '2014' },
                { checked: false, text: '2013' },
                { checked: false, text: '2012' },
                { checked: false, text: '2011' },
                { checked: false, text: '2010' },
                { checked: false, text: '2009' },
                { checked: false, text: '2008' },
                { checked: false, text: '2007' },
            ],
            city: [
                { checked: true, text: '全部地区' },
                { checked: false, text: '大陆' },
                { checked: false, text: '香港' },
                { checked: false, text: '台湾' },
                { checked: false, text: '美国' },
                { checked: false, text: '韩国' },
                { checked: false, text: '日本' },
                { checked: false, text: '泰国' },
                { checked: false, text: '新加坡' },
                { checked: false, text: '马来西亚' },
                { checked: false, text: '印度' },
                { checked: false, text: '英国' },
                { checked: false, text: '法国' },
                { checked: false, text: '加拿大' },
                { checked: false, text: '西班牙' },
                { checked: false, text: '俄罗斯' },
                { checked: false, text: '其它' },
            ],
            language: [
                { checked: true, text: '全部语言' },
                { checked: false, text: '国语' },
                { checked: false, text: '英语' },
                { checked: false, text: '粤语' },
                { checked: false, text: '闽南语' },
                { checked: false, text: '韩语' },
                { checked: false, text: '日语' },
                { checked: false, text: '法语' },
                { checked: false, text: '德语' },
                { checked: false, text: '其它' },
            ],
            sort: [
                { checked: true, text: '更新排序' },
                { checked: false, text: '人气排序' },
            ]
        }
    },
    {
        title: '动漫',
        obj: {
            type: [],
            year: [
                { checked: true, text: '全部年代' },
                { checked: false, text: '2021' },
                { checked: false, text: '2020' },
                { checked: false, text: '2019' },
                { checked: false, text: '2018' },
                { checked: false, text: '2017' },
                { checked: false, text: '2016' },
                { checked: false, text: '2015' },
                { checked: false, text: '2014' },
                { checked: false, text: '2013' },
                { checked: false, text: '2012' },
                { checked: false, text: '2011' },
                { checked: false, text: '2010' },
                { checked: false, text: '2009' },
                { checked: false, text: '2008' },
                { checked: false, text: '2007' },
            ],
            city: [
                { checked: true, text: '全部地区' },
                { checked: false, text: '大陆' },
                { checked: false, text: '香港' },
                { checked: false, text: '台湾' },
                { checked: false, text: '美国' },
                { checked: false, text: '韩国' },
                { checked: false, text: '日本' },
                { checked: false, text: '泰国' },
                { checked: false, text: '新加坡' },
                { checked: false, text: '马来西亚' },
                { checked: false, text: '印度' },
                { checked: false, text: '英国' },
                { checked: false, text: '法国' },
                { checked: false, text: '加拿大' },
                { checked: false, text: '西班牙' },
                { checked: false, text: '俄罗斯' },
                { checked: false, text: '其它' },
            ],
            language: [
                { checked: true, text: '全部语言' },
                { checked: false, text: '国语' },
                { checked: false, text: '英语' },
                { checked: false, text: '粤语' },
                { checked: false, text: '闽南语' },
                { checked: false, text: '韩语' },
                { checked: false, text: '日语' },
                { checked: false, text: '法语' },
                { checked: false, text: '德语' },
                { checked: false, text: '其它' },
            ],
            sort: [
                { checked: true, text: '更新排序' },
                { checked: false, text: '人气排序' },
            ]
        }
    },
    {
        title: '综艺',
        obj: {
            type: [],
            year: [
                { checked: true, text: '全部年代' },
                { checked: false, text: '2021' },
                { checked: false, text: '2020' },
                { checked: false, text: '2019' },
                { checked: false, text: '2018' },
                { checked: false, text: '2017' },
                { checked: false, text: '2016' },
                { checked: false, text: '2015' },
                { checked: false, text: '2014' },
                { checked: false, text: '2013' },
                { checked: false, text: '2012' },
                { checked: false, text: '2011' },
                { checked: false, text: '2010' },
                { checked: false, text: '2009' },
                { checked: false, text: '2008' },
                { checked: false, text: '2007' },
            ],
            city: [
                { checked: true, text: '全部地区' },
                { checked: false, text: '大陆' },
                { checked: false, text: '香港' },
                { checked: false, text: '台湾' },
                { checked: false, text: '美国' },
                { checked: false, text: '韩国' },
                { checked: false, text: '日本' },
                { checked: false, text: '泰国' },
                { checked: false, text: '新加坡' },
                { checked: false, text: '马来西亚' },
                { checked: false, text: '印度' },
                { checked: false, text: '英国' },
                { checked: false, text: '法国' },
                { checked: false, text: '加拿大' },
                { checked: false, text: '西班牙' },
                { checked: false, text: '俄罗斯' },
                { checked: false, text: '其它' },
            ],
            language: [
                { checked: true, text: '全部语言' },
                { checked: false, text: '国语' },
                { checked: false, text: '英语' },
                { checked: false, text: '粤语' },
                { checked: false, text: '闽南语' },
                { checked: false, text: '韩语' },
                { checked: false, text: '日语' },
                { checked: false, text: '法语' },
                { checked: false, text: '德语' },
                { checked: false, text: '其它' },
            ],
            sort: [
                { checked: true, text: '更新排序' },
                { checked: false, text: '人气排序' },
            ]
        }
    }
]

